#!/bin/bash

counter=0
start_date="2024-02-10T10:00:00"  # Adjust this to your desired start date

for file in $(git diff --cached --name-only); do
    commit_date=$(date -d "$start_date + $counter days" +"%Y-%m-%dT%H:%M:%S")
    
    GIT_COMMITTER_DATE="$commit_date" git commit -m "Added $(basename "$file")" --date "$commit_date"
    
    ((counter++))
done
